nodeLinker: "node-modules"

# enabling global cache to avoid generating .yarn ???
# 
# reference from https://yarnpkg.com/features/zero-installs
# If at some point you decide that in the end you prefer to keep using a global cache, just toggle on enableGlobalCache in the yarnrc settings and it'll be back to normal.
enableGlobalCache: true